<a href="https://colab.research.google.com/github/Likhita-T/FutureMakers/blob/main/Upsampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# define model
from keras.models import Sequential
from keras.layers import UpSampling2D
model = Sequential()
model.add(UpSampling2D())

In [7]:
# define input data
import numpy as np
X = np.asarray([[1, 2],
			 [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [8]:
# reshape input data
X = X.reshape((1, 2, 2, 1))

In [9]:
# define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))
# summarize the model
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [10]:
# make a prediction with the model
yhat = model.predict(X)

In [11]:
yhat = yhat.reshape((4, 4))
# summarize output
print(yhat)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [12]:
# using different scale factors for each dimension
model.add(UpSampling2D(size=(2, 3)))

In [16]:
# Generator Model With the UpSampling2D Layer
from keras.layers import Dense, Reshape
model = Sequential()
model.add(Dense(128 * 5 * 5, input_dim=100))
model.add(Reshape((5, 5, 128)))

In [17]:
model.add(UpSampling2D())

In [19]:
from keras.layers import Conv2D
model.add(Conv2D(1, (3,3), padding='same'))

In [20]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_3 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


In [22]:
# Conv2DTranspose Layer
from keras.layers import Conv2DTranspose
model = Sequential()
model.add(Dense(128 * 5 * 5, input_dim=100))
model.add(Reshape((5, 5, 128)))
model.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_2 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose (Conv2DTran (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
